### ISSUE TITLE
Ready to use?

### ISSUE THREAD

**Issue by ghost** [ananace/matrix-synapse#1]
Hey,

Previously I've used the debian packaged for matrix but after a while my instance started freezing and eating all my RAM at startup. I've wanted to switch for a solution that requires less maintenance and just provides me with a matrix server that I can use as a meta-messanger for different IM services (telegra/whatsapp/skype/discord/slack/fb messanger). Is this project suitable and ready for this kind of use case?

Thanks.

**Comment by ananace** [comment]
My main focus has been on doing a package that can be easily run on a Kubernetes cluster, though because of Synapse's IO requirements it would probably be quite expensive to use this on a hosted cluster. And sadly it's not quite one-click-install yet either, I've had a few issues with how K8s mounts sub-path volumes that I've yet to figure out a perfect way to solve.

I myself am using it to run two Matrix HSes though, `kittenface.studio` and `ctrl-c.liu.se`, and while both are quite well used neither has any application services at the moment. I'll probably write up how to do ASes properly with K8s at a later date, when I set one up for either of the servers.

It is worth mentioning that system usage is not going to drop if you want to use Docker/Kubernetes to host your Synapse, it's still the same application after all, only with some a few layers of indirection beneath.

**Comment by ghost** [comment]
> It is worth mentioning that system usage is not going to drop if you want to use Docker/Kubernetes to host your Synapse, it's still the same application after all, only with some a few layers of indirection beneath.

I'm aware, but with docker I can set limits on the ram/cpu usage and let it sort itself out for a while, when now the host becomes unusable.

**Comment by ananace** [comment]
Well, to answer the original question again;

It should be fully ready for use, though if you don't particularly need the additions that this sets over the original docker image then you could also use that one. The differences I've built for this setup are mainly for ease-of-use when it comes to running workers, getting logging out of the container, and easing configuration without direct filesystem access.
