### ISSUE TITLE
Ready for use?

### ISSUE THREAD

**Issue by danilorsilva** [ananace/matrix-synapse#4]
Hello,

     This files are updated and ready for use?

Thanks!

**Comment by ananace** [comment]
The image is currently in use by multiple Matrix installations, though the example manifests are not updated with the latest available image version.

**Comment by danilorsilva** [comment]
Thanks for your attention.

Are the yaml files updated? I will replace de image for the latest one(1.12.4) and configure the configmap and secret. 

I think that is it, right?

Thank you one more time.

**Comment by ananace** [comment]
That should be enough to get an install up and running, yes.

The YAML should still be up-to-date in that regard, though image versions are not updated as you seem to have noticed.
I've built the example YAMLs from sanitized data on my local install, and I've not changed anything but image version since the last time I updated them.

Also, the latest is now 1.13.0 :smiley:

**Comment by danilorsilva** [comment]
Thanks!
